[package]
name = "mdstream"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-width = "0.1"
syntect = "5.2"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
